drop database if exists DBSA;
create database DBSA;
use DBSA;



CREATE TABLE USUARIO(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(32) NOT NULL,
    TIPO_USUARIO VARCHAR(7) NOT NULL,
    PRIMARY KEY(ID_USUARIO)
);

CREATE TABLE RECEITA(
	ID_RECEITA INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
	-- TIPO VARCHAR(45) NOT NULL,
    IMAGEM VARCHAR(300),
    TITULO VARCHAR(100) NOT NULL,
    PORCAO VARCHAR(100),
    PRIMARY KEY(ID_RECEITA, ID_USUARIO),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE INGREDIENTE(
	ID_INGREDIENTE INT NOT NULL AUTO_INCREMENT,
    ID_RECEITA INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
    
    PRIMARY KEY(ID_INGREDIENTE, ID_RECEITA),
    FOREIGN KEY(ID_RECEITA) REFERENCES RECEITA(ID_RECEITA)
);


CREATE TABLE PASSOS(
	ID_PASSOS INT NOT NULL AUTO_INCREMENT,
    ID_RECEITA INT NOT NULL,
    DESCRICAO VARCHAR(100),
    NUMERO INT,
    PRIMARY KEY(ID_PASSOS,ID_RECEITA),
    FOREIGN KEY(ID_RECEITA) REFERENCES RECEITA(ID_RECEITA)
);




INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA, TIPO_USUARIO)
VALUES (1, 'Mateus Rocha', 'matheus@gmail.com', 'cabrito123', 'USUARIO');
INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA, TIPO_USUARIO)
VALUES (2, 'João Ricardo', 'jonas@gmail.com', 'monica123', 'USUARIO');
INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA, TIPO_USUARIO)
VALUES (3, 'Dudu Gonzalez', 'dudu@gmail.com', 'dudu1234', 'USUARIO');
INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA, TIPO_USUARIO)
VALUES (4, 'Admin Marcos', 'marcos@gmail.com', 'admin123', 'ADMIN');

INSERT INTO RECEITA(ID_USUARIO, IMAGEM, TITULO, PORCAO)
VALUES (4, 'https://s2.glbimg.com/DnsDp5_cwUYLCQ8O3WqsKWaBVMU=/0x0:300x225/984x0/smart/filters:strip_icc()/s.glbimg.com/po/rc/media/2013/02/20/10_17_21_740_Banana_Frita.jpg', 'BANANA FRITA', 'rende 30');

INSERT INTO INGREDIENTE(ID_RECEITA, NOME) 
VALUES(1, '1 Ovo');

INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (1, 'COLOQUE NA FRIGIDEIRA', 1);

INSERT INTO RECEITA(ID_USUARIO, IMAGEM, TITULO, PORCAO)
VALUES (4, 'https://beagaembalagem.com.br/wp-content/uploads/2021/06/batata-frita.jpeg', 'Batata Frita', 'rende 30');

SELECT * FROM RECEITA;
SELECT * FROM INGREDIENTE;
SELECT * FROM PASSOS;

