drop database if exists DBSA;
create database DBSA;
use DBSA;

CREATE TABLE ADMINISTRADOR(
	ID_ADMIN INT NOT NULL auto_increment,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(32) NOT NULL,
    PRIMARY KEY(ID_ADMIN)
);

CREATE TABLE ALERGIA(
	ID_ALERGIA VARCHAR(45) NOT NULL,
    PRIMARY KEY(ID_ALERGIA)
);

CREATE TABLE USUARIO(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    SENHA VARCHAR(32) NOT NULL,
    PRIMARY KEY(ID_USUARIO)
);

CREATE TABLE INGREDIENTE(
	ID_INGREDIENTE VARCHAR(45) NOT NULL,
    ID_ALERGIA VARCHAR(45),
    PRIMARY KEY(ID_INGREDIENTE),
    FOREIGN KEY(ID_ALERGIA) REFERENCES ALERGIA(ID_ALERGIA)
    
);

CREATE TABLE RECEITA(
	ID_RECEITA INT NOT NULL AUTO_INCREMENT,
	TIPO VARCHAR(45) NOT NULL,
    IMAGEM MEDIUMBLOB,
    TITULO VARCHAR(100) NOT NULL,
    PORCAO VARCHAR(100),
    PRIMARY KEY(ID_RECEITA)
);

CREATE TABLE PASSOS(
	ID_PASSOS INT NOT NULL,
    ID_RECEITA INT NOT NULL,
    DESCRICAO VARCHAR(150),
    TEMPO INT,
    DOSAGEM INT,
    UNIDADE_DE_MEDIDA VARCHAR(45),
    PRIMARY KEY(ID_PASSOS,ID_RECEITA),
    FOREIGN KEY(ID_RECEITA) REFERENCES RECEITA(ID_RECEITA)
);

CREATE TABLE INGREDIENTE_ARMAZENAR_RECEITA(
	ID_INGREDIENTE VARCHAR(45) NOT NULL,
    ID_RECEITA INT NOT NULL,
	FOREIGN KEY(ID_INGREDIENTE) REFERENCES INGREDIENTE(ID_INGREDIENTE),
    FOREIGN KEY(ID_RECEITA) REFERENCES RECEITA(ID_RECEITA)
);

CREATE TABLE RECEITA_SALVAR_USUARIO(
	ID_RECEITA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY(ID_RECEITA,ID_USUARIO),
    FOREIGN KEY(ID_RECEITA) REFERENCES RECEITA(ID_RECEITA),
    FOREIGN  KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)	
);

CREATE TABLE RECEITA_AVALIAR_USUARIO(
	ID_AVALIAR INT NOT NULL,
    ID_RECEITA INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    NOTA INT NOT NULL,
    PRIMARY KEY(ID_AVALIAR,ID_RECEITA,ID_USUARIO),
    FOREIGN KEY(ID_RECEITA) REFERENCES RECEITA(ID_RECEITA),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE ALERGIA_POSSUIR_USUARIO(
	ID_ALERGIA VARCHAR(45) NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY(ID_ALERGIA,ID_USUARIO),
    FOREIGN KEY(ID_ALERGIA) REFERENCES ALERGIA(ID_ALERGIA),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA)
VALUES (1, 'Mateus Rocha', 'matheus@gmail.com', 'cabrito123');
INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA)
VALUES (2, 'Gabriel Rocha', 'gabs@gmail.com', 'lulu123456');
INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA)
VALUES (3, 'Dudu Rocha', 'dudu@gmail.com', 'dudujogo1234');


